project: 
  type: website
  output-dir: "."

website:
  title: "B.H. CHOE"
  navbar:
    pinned: true
    left:
      - text: Project
        href: project.qmd
      - text: Dashboard
        href: quarto-dashboard.qmd
      - text: Blog
        href: blog-listing.qmd
            
  page-footer: 
    center: "Powered with GitHub and Quarto<br>© Byeong-Hak Choe, 2024"

format:
  html:
    theme: 
      light: flatly # flatly
      dark: [darkly, theme-dark.scss] # darkly
    mainfont: system-ui; 
    highlight-style: atom-one
    css: styles.css
    toc: false
    include-after-body: target_blank.html
    
